-- PostgreSQL schema for raihankalla.id Supabase database
-- Generated from live DB: aws-0-ap-southeast-1.pooler.supabase.com

-- Table: liked_videos
CREATE TABLE IF NOT EXISTS liked_videos (
    id SERIAL PRIMARY KEY,
    title TEXT,
    url TEXT UNIQUE,
    video_owner_channel_id TEXT,
    video_owner_channel_title TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    thumbnail_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: github_stars
CREATE TABLE IF NOT EXISTS github_stars (
    repo_id BIGINT PRIMARY KEY,
    full_name TEXT UNIQUE,
    html_url TEXT,
    description TEXT,
    language TEXT,
    stargazers_count INTEGER,
    forks_count INTEGER,
    pushed_at TIMESTAMP WITH TIME ZONE,
    owner_login TEXT,
    owner_avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    starred_at TIMESTAMP WITH TIME ZONE,
    star_list_names TEXT[]
);

-- Table: chrome_bookmarks
CREATE TABLE IF NOT EXISTS chrome_bookmarks (
    id SERIAL PRIMARY KEY,
    name TEXT,
    type VARCHAR(10) CHECK (type IN ('url', 'folder')),
    url TEXT,
    date_added BIGINT,
    parent_id INTEGER REFERENCES chrome_bookmarks(id) ON DELETE CASCADE,
    source TEXT,
    path TEXT,
    parent_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: x_tweets
CREATE TABLE IF NOT EXISTS x_tweets (
    id TEXT PRIMARY KEY,
    is_bookmark BOOLEAN DEFAULT FALSE,
    is_like BOOLEAN DEFAULT FALSE,
    is_retweet BOOLEAN DEFAULT FALSE,
    author_id TEXT NOT NULL,
    text TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    edit_history_tweet_ids TEXT[],
    retweet_count INTEGER DEFAULT 0,
    reply_count INTEGER DEFAULT 0,
    like_count INTEGER DEFAULT 0,
    quote_count INTEGER DEFAULT 0,
    bookmark_count INTEGER DEFAULT 0,
    impression_count INTEGER DEFAULT 0,
    article_title TEXT,
    entities JSONB DEFAULT '{}',
    synced_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT valid_type CHECK (is_bookmark = TRUE OR is_like = TRUE OR is_retweet = TRUE)
);

-- Table: reading_list
CREATE TABLE IF NOT EXISTS reading_list (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    title TEXT,
    has_been_read BOOLEAN DEFAULT FALSE,
    creation_time BIGINT,
    last_update_time BIGINT,
    synced_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reading_list_url ON reading_list (url);
CREATE INDEX IF NOT EXISTS idx_reading_list_read_status ON reading_list (has_been_read);

-- Table: users
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    mysql_config JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    google_api_key TEXT
);

-- Table: finance_tracker
CREATE TABLE IF NOT EXISTS finance_tracker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(255) UNIQUE,            -- User email from Google OAuth authentication
    avatar TEXT,                          -- URL to user Google profile picture
    sheet_id VARCHAR(255),                -- Google Sheets ID for user personal expense tracking sheet
    expense_categories JSONB DEFAULT '[{"icon":"Utensils","label":"Food & Beverages","value":"🍔 Food & Beverages"},{"icon":"Donut","label":"Snacks","value":"🥫 Snacks"},{"icon":"Baby","label":"Baby","value":"👼🏼 Baby"},{"icon":"ShoppingBasket","label":"Groceries","value":"🛒 Groceries"},{"icon":"Bus","label":"Transportation","value":"🚗 Transportation"},{"icon":"Book","label":"Education","value":"🎓 Education"},{"icon":"Tv","label":"Entertainment","value":"🍿 Entertainment"},{"icon":"Gift","label":"Gift & Donations","value":"🎁 Gift & Donations"},{"icon":"Users","label":"Family","value":"😊 Family"},{"icon":"Heart","label":"Health","value":"💊 Health"},{"icon":"FileText","label":"Bill & Utilities","value":"🧾 Bill & Utilities"},{"icon":"DollarSign","label":"Fees & Charges","value":"💵 Fees & Charges"},{"icon":"ShoppingBag","label":"Shopping","value":"🛍️ Shopping"},{"icon":"ChartArea","label":"Investment","value":"💰 Investment"},{"icon":"Home","label":"Accommodation","value":"🏠 Accommodation"},{"icon":"Dices","label":"Others","value":"🎲 Others"}]', -- User customizable expense categories stored as JSON array
    income_categories JSONB DEFAULT '[{"icon":"Banknote","label":"Salary","value":"💰 Salary"},{"icon":"PenLine","label":"Event","value":"✍🏼 Event"},{"icon":"BriefcaseBusiness","label":"Business","value":"💼 Business"},{"icon":"Landmark","label":"Gift","value":"🎁 Gift"},{"icon":"Dices","label":"Others","value":"🎲 Others"}]', -- User customizable income categories stored as JSON array
    monthly_budget NUMERIC(15,2) DEFAULT 0.00, -- User monthly budget limit in decimal format
    preferences JSONB DEFAULT '{}',       -- Additional user preferences and settings as JSON
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_finance_tracker_email ON finance_tracker (email);
CREATE INDEX IF NOT EXISTS idx_finance_tracker_sheet_id ON finance_tracker (sheet_id);
CREATE INDEX IF NOT EXISTS idx_finance_tracker_is_active ON finance_tracker (is_active);

-- Table: mindmaps
CREATE TABLE IF NOT EXISTS mindmaps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT,
    input_type TEXT NOT NULL,
    pdf_url TEXT,
    file_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    source_url TEXT,
    is_example BOOLEAN DEFAULT FALSE,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT now() + INTERVAL '24 hours',
    parsed_pdf_content TEXT
);

-- Table: mindmap_nodes
CREATE TABLE IF NOT EXISTS mindmap_nodes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mindmap_id UUID NOT NULL REFERENCES mindmaps(id) ON DELETE CASCADE,
    node_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    parent_id TEXT,
    level INTEGER NOT NULL,
    page_number INTEGER,
    position_x DOUBLE PRECISION,
    position_y DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mindmap_nodes_mindmap_id ON mindmap_nodes (mindmap_id);
CREATE INDEX IF NOT EXISTS idx_mindmap_nodes_parent_id ON mindmap_nodes (parent_id);
