export const featuredProjects = [
  {
    title: "Kekayaan Bahasa Nusantara",
    subtitle: "",
    url: "/bahasa-nusantara",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/bahasa-nusantara.png?updatedAt=1771319978903",
  },
  {
    title: "Media Effects on the 2019 Election",
    subtitle: "",
    url: "/scrolly-demo",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/media-election-2019.png",
  },
  {
    title: "Good News Garden - Playful Narrative 3D Network",
    subtitle: "",
    url: "https://alhrkn.vercel.app/goodnews-garden",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/goodnews-garden.png",
  },
  {
    title: "Jakarta Labor Market Analysis (19K+ Job Postings)",
    subtitle: "",
    url: "/labor-market-analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/job-market-analysis.png",
  },
  {
    title: "National Budget Progression",
    subtitle: "",
    url: "/national-budget",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/national-budget.png",
  },
  {
    title: "Economic Growth vs Envinromental Impact",
    subtitle: "",
    url: "/pdrb-iklh",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/pdrb-iklh.png",
  },
  {
    title: "Good News - Bibliometrics Analysis",
    subtitle: "",
    url: "/goodnews-bibliometrics",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/goodnews-bibliometrics.png",
  },
  {
    title: "TurnBackHoax Analysis of 2025: Narrative 3D Network",
    subtitle: "",
    url: "https://alhrkn.vercel.app/hoax-network",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2025-network.png",
  },
  {
    title: "TurnBackHoax Analysis of 2024 (Topic Modeling)",
    subtitle: "",
    url: "/turnbackhoax-analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2024-topic-modeling.png",
  },
  {
    title: "TurnBackHoax Analysis of 2024: Text Network",
    subtitle: "",
    url: "/turnbackhoax-text-network",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2024-network.png",
  },
  {
    title: "TurnBackHoax Analysis of 2024: Sentiment Analysis",
    subtitle: "",
    url: "/turnbackhoax-sentiment-analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2024-sentiment-chart.png",
  },
  {
    title: "Green Financing for SMEs - Survey Report",
    subtitle: "",
    url: "/BRIN-Survey-Report",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/green-finance-2.png",
  },
  {
    title: "Green Financing for SMEs - Quantitative Analysis",
    subtitle: "",
    url: "/BRIN-Quantitative-Analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/green-finance-1.png",
  },
  {
    title: "Green Financing for SMEs - CrossTab Analysis",
    subtitle: "",
    url: "/BRIN-CrossTab-Analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/green-finance-3.png",
  },
];
