const sortByDate = true;

const rawProjects = [
  {
    title: "Kekayaan Bahasa Nusantara",
    subtitle: "",
    type: "visualization",
    date: "2026-02-17",
    url: "/bahasa-nusantara",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/bahasa-nusantara.png?updatedAt=1771319978903",
  },
  {
    title: "Media Effects on Election",
    subtitle: "",
    type: "research",
    date: "2026-02-24",
    url: "/media-effects-election",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/media-election-2019.png",
  },
  {
    title: "Good News Garden - Playful Narrative 3D Network",
    subtitle: "",
    type: "visualization",
    date: "2026-02-08",
    url: "https://alhrkn.vercel.app/goodnews-garden",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/goodnews-garden.png",
  },
  {
    title: "Jakarta Job Market Analysis (19K+ Vacancies)",
    subtitle: "",
    type: "analysis",
    date: "2026-02-04",
    url: "/labor-market-analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/job-market-analysis-2.png",
  },
  {
    title: "National Budget Progression",
    subtitle: "",
    type: "visualization",
    date: "2026-02-21",
    url: "/national-budget",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/national-budget.png",
  },
  {
    title: "Economic Growth vs Envinromental Impact",
    subtitle: "",
    type: "analysis",
    date: "2026-01-02",
    url: "/pdrb-iklh",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/pdrb-iklh.png",
  },
  {
    title: "Google Trends' Election Prediction Power",
    subtitle: "",
    type: "analysis",
    date: "2026-03-10",
    url: "/google-trends-prediction",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/google-trends-election.png",
  },
  {
    title: "ESG Perception Analysis",
    subtitle: "",
    type: "research",
    date: "2026-03-17",
    url: "/esg-perception",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/esg-perception.png",
  },
  {
    title: "IDR Exchange Trend",
    subtitle: "",
    type: "visualization",
    date: "2026-03-19",
    url: "/idr-exchange",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/idr-exchange.png",
  },
  {
    title: "Good News - Bibliometrics Analysis",
    subtitle: "",
    type: "analysis",
    date: "2026-02-10",
    url: "/goodnews-bibliometrics",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/goodnews-bibliometrics-2.png",
  },
  {
    title: "TurnBackHoax Analysis of 2025: Narrative 3D Network",
    subtitle: "",
    type: "visualization",
    date: "2026-01-21",
    url: "https://alhrkn.vercel.app/hoax-network",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2025-network.png",
  },
  {
    title: "TurnBackHoax Analysis of 2024 (Topic Modeling)",
    subtitle: "",
    type: "research",
    date: "2025-11-24",
    url: "/turnbackhoax-analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2024-topic-modeling.png",
  },
  {
    title: "TurnBackHoax Analysis of 2024: Text Network",
    subtitle: "",
    type: "visualization",
    date: "2025-11-25",
    url: "/turnbackhoax-text-network",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2024-network.png",
  },
  {
    title: "TurnBackHoax Analysis of 2024: Sentiment Analysis",
    subtitle: "",
    type: "analysis",
    date: "2025-11-25",
    url: "/turnbackhoax-sentiment-analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hoax-2024-sentiment-chart.png",
  },
  {
    title: "Green Financing for SMEs - Survey Report",
    subtitle: "",
    type: "analysis",
    date: "2026-01-16",
    url: "/BRIN-Survey-Report",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/green-finance-2.png",
  },
  {
    title: "Green Financing for SMEs - Quantitative Analysis",
    subtitle: "",
    type: "analysis",
    date: "2026-01-16",
    url: "/BRIN-Quantitative-Analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/green-finance-1.png",
  },
  {
    title: "Green Financing for SMEs - CrossTab Analysis",
    subtitle: "",
    type: "analysis",
    date: "2026-01-18",
    url: "/BRIN-CrossTab-Analysis",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/green-finance-3.png",
  },
  {
    title: "Human Capital Development Plan Dashboard",
    subtitle: "",
    type: "analysis",
    date: "2026-03-01",
    url: "/hcdp-dashboard",
    coverImage: "https://ik.imagekit.io/raihankalla/research_section_cover/hcdp-dashboard.png",
  }
];

export const featuredProjects = sortByDate
  ? [...rawProjects].sort((a, b) => new Date(b.date || 0).getTime() - new Date(a.date || 0).getTime())
  : rawProjects;

